# Generated by Django 4.1.7 on 2023-03-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocenki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_objects', models.CharField(choices=[('przyroda', 'przyroda'), ('matma', 'matma'), ('fizyka', 'fizyka'), ('plastyka', 'plastyka')], max_length=30)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '5')], max_length=30)),
                ('weight', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '5')], max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
